"""create canonical foundation schema

Revision ID: 2a8a78d61842
Revises:
Create Date: 2026-09-04 04:21:23.864689
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2a8a78d61842"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buyers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("external_identity", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buyers")),
        sa.UniqueConstraint("external_identity", name=op.f("uq_buyers_external_identity")),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("operation", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("response_body_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "actor_id", "operation", "idempotency_key", name=op.f("uq_idempotency_records_actor_id")
        ),
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
    )
    op.create_table(
        "merchant_policies",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("auto_accept_max_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "auto_accept_max_minor IS NULL OR auto_accept_max_minor >= 0",
            name=op.f("ck_merchant_policies_limit_nonnegative"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_merchant_policies_version_positive")),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_merchant_policies_merchant_id_merchants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchant_policies")),
        sa.UniqueConstraint(
            "merchant_id", "version", name=op.f("uq_merchant_policies_merchant_id")
        ),
    )
    op.create_index(
        op.f("ix_merchant_policies_merchant_id"), "merchant_policies", ["merchant_id"], unique=False
    )
    op.create_table(
        "merchant_users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], name=op.f("fk_merchant_users_merchant_id_merchants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchant_users")),
        sa.UniqueConstraint("merchant_id", "user_id", name=op.f("uq_merchant_users_merchant_id")),
    )
    op.create_index(
        op.f("ix_merchant_users_merchant_id"), "merchant_users", ["merchant_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("sku", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("available_quantity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("available_quantity >= 0", name=op.f("ck_products_stock_nonnegative")),
        sa.CheckConstraint("length(currency) = 3", name=op.f("ck_products_currency_length")),
        sa.CheckConstraint("price_minor >= 0", name=op.f("ck_products_price_nonnegative")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_products_version_positive")),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], name=op.f("fk_products_merchant_id_merchants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("merchant_id", "sku", name=op.f("uq_products_merchant_id")),
    )
    op.create_index(op.f("ix_products_merchant_id"), "products", ["merchant_id"], unique=False)
    op.create_index(
        "ix_products_merchant_status", "products", ["merchant_id", "status"], unique=False
    )
    op.create_table(
        "product_images",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("public_url", sa.String(length=2048), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_product_images_sort_order_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], name=op.f("fk_product_images_merchant_id_merchants")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_images_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
        sa.UniqueConstraint("product_id", "sort_order", name=op.f("uq_product_images_product_id")),
        sa.UniqueConstraint("storage_path", name=op.f("uq_product_images_storage_path")),
    )
    op.create_index(
        op.f("ix_product_images_merchant_id"), "product_images", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_images_product_id"), "product_images", ["product_id"], unique=False
    )
    op.create_table(
        "product_metadata",
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("attributes_json", sa.JSON(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_metadata_product_id_products")
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_product_metadata")),
    )
    op.create_table(
        "purchase_proposals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("buyer_id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("product_version", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_minor", sa.Integer(), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("proposal_hash", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(currency) = 3", name=op.f("ck_purchase_proposals_currency_length")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_proposals_quantity_positive")),
        sa.CheckConstraint(
            "total_minor >= 0", name=op.f("ck_purchase_proposals_total_nonnegative")
        ),
        sa.CheckConstraint(
            "unit_price_minor >= 0", name=op.f("ck_purchase_proposals_unit_price_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["buyers.id"], name=op.f("fk_purchase_proposals_buyer_id_buyers")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_purchase_proposals_merchant_id_merchants"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_purchase_proposals_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_proposals")),
        sa.UniqueConstraint("proposal_hash", name=op.f("uq_purchase_proposals_proposal_hash")),
    )
    op.create_index(
        op.f("ix_purchase_proposals_buyer_id"), "purchase_proposals", ["buyer_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_proposals_merchant_id"),
        "purchase_proposals",
        ["merchant_id"],
        unique=False,
    )
    op.create_table(
        "buyer_authorizations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("buyer_id", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("proposal_hash", sa.String(length=128), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("max_quantity", sa.Integer(), nullable=False),
        sa.Column("max_amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("authorized_by", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_amount_minor >= 0", name=op.f("ck_buyer_authorizations_amount_nonnegative")
        ),
        sa.CheckConstraint(
            "max_quantity > 0", name=op.f("ck_buyer_authorizations_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["buyers.id"], name=op.f("fk_buyer_authorizations_buyer_id_buyers")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_buyer_authorizations_merchant_id_merchants"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_buyer_authorizations_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["purchase_proposals.id"],
            name=op.f("fk_buyer_authorizations_proposal_id_purchase_proposals"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buyer_authorizations")),
    )
    op.create_index(
        op.f("ix_buyer_authorizations_buyer_id"), "buyer_authorizations", ["buyer_id"], unique=False
    )
    op.create_index(
        op.f("ix_buyer_authorizations_proposal_id"),
        "buyer_authorizations",
        ["proposal_id"],
        unique=False,
    )
    op.create_table(
        "merchant_decisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("decided_by", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_merchant_decisions_merchant_id_merchants"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["merchant_policies.id"],
            name=op.f("fk_merchant_decisions_policy_id_merchant_policies"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["purchase_proposals.id"],
            name=op.f("fk_merchant_decisions_proposal_id_purchase_proposals"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchant_decisions")),
    )
    op.create_index(
        op.f("ix_merchant_decisions_merchant_id"),
        "merchant_decisions",
        ["merchant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_merchant_decisions_proposal_id"),
        "merchant_decisions",
        ["proposal_id"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("buyer_authorization_id", sa.String(length=64), nullable=True),
        sa.Column("merchant_decision_id", sa.String(length=64), nullable=True),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("buyer_id", sa.String(length=64), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_transactions_amount_nonnegative")),
        sa.CheckConstraint(
            "length(currency) = 3", name=op.f("ck_transactions_currency_length")
        ),
        sa.ForeignKeyConstraint(
            ["buyer_authorization_id"],
            ["buyer_authorizations.id"],
            name=op.f("fk_transactions_buyer_authorization_id_buyer_authorizations"),
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["buyers.id"], name=op.f("fk_transactions_buyer_id_buyers")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_decision_id"],
            ["merchant_decisions.id"],
            name=op.f("fk_transactions_merchant_decision_id_merchant_decisions"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], name=op.f("fk_transactions_merchant_id_merchants")
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["purchase_proposals.id"],
            name=op.f("fk_transactions_proposal_id_purchase_proposals"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("proposal_id", name=op.f("uq_transactions_proposal_id")),
    )
    op.create_index(op.f("ix_transactions_buyer_id"), "transactions", ["buyer_id"], unique=False)
    op.create_index(
        op.f("ix_transactions_merchant_id"), "transactions", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_transactions_merchant_state", "transactions", ["merchant_id", "state"], unique=False
    )
    op.create_table(
        "payment_attempts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.String(length=64), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_request_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("provider_order_id", sa.String(length=255), nullable=True),
        sa.Column("provider_payment_id", sa.String(length=255), nullable=True),
        sa.Column("provider_order_state", sa.String(length=64), nullable=True),
        sa.Column("provider_payment_state", sa.String(length=64), nullable=True),
        sa.Column("capture_state", sa.String(length=64), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt_number > 0", name=op.f("ck_payment_attempts_attempt_positive")),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_payment_attempts_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_attempts")),
        sa.UniqueConstraint(
            "provider", "provider_order_id", name=op.f("uq_payment_attempts_provider")
        ),
        sa.UniqueConstraint(
            "transaction_id", "attempt_number", name=op.f("uq_payment_attempts_transaction_id")
        ),
    )
    op.create_index(
        op.f("ix_payment_attempts_transaction_id"),
        "payment_attempts",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "provider_webhooks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_event_id", sa.String(length=255), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("payload_hash", sa.String(length=128), nullable=False),
        sa.Column("transaction_id", sa.String(length=64), nullable=True),
        sa.Column("processing_status", sa.String(length=32), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_provider_webhooks_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_webhooks")),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name=op.f("uq_provider_webhooks_provider")
        ),
    )
    op.create_index(
        op.f("ix_provider_webhooks_transaction_id"),
        "provider_webhooks",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "transaction_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("actor_type", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("previous_state", sa.String(length=40), nullable=True),
        sa.Column("new_state", sa.String(length=40), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("provider_reference_redacted", sa.String(length=255), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_transaction_events_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_events")),
    )
    op.create_index(
        op.f("ix_transaction_events_correlation_id"),
        "transaction_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_events_transaction_id"),
        "transaction_events",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_events_transaction_id"), table_name="transaction_events")
    op.drop_index(op.f("ix_transaction_events_correlation_id"), table_name="transaction_events")
    op.drop_table("transaction_events")
    op.drop_index(op.f("ix_provider_webhooks_transaction_id"), table_name="provider_webhooks")
    op.drop_table("provider_webhooks")
    op.drop_index(op.f("ix_payment_attempts_transaction_id"), table_name="payment_attempts")
    op.drop_table("payment_attempts")
    op.drop_index("ix_transactions_merchant_state", table_name="transactions")
    op.drop_index(op.f("ix_transactions_merchant_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_buyer_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_merchant_decisions_proposal_id"), table_name="merchant_decisions")
    op.drop_index(op.f("ix_merchant_decisions_merchant_id"), table_name="merchant_decisions")
    op.drop_table("merchant_decisions")
    op.drop_index(op.f("ix_buyer_authorizations_proposal_id"), table_name="buyer_authorizations")
    op.drop_index(op.f("ix_buyer_authorizations_buyer_id"), table_name="buyer_authorizations")
    op.drop_table("buyer_authorizations")
    op.drop_index(op.f("ix_purchase_proposals_merchant_id"), table_name="purchase_proposals")
    op.drop_index(op.f("ix_purchase_proposals_buyer_id"), table_name="purchase_proposals")
    op.drop_table("purchase_proposals")
    op.drop_table("product_metadata")
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_merchant_id"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_index("ix_products_merchant_status", table_name="products")
    op.drop_index(op.f("ix_products_merchant_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_merchant_users_merchant_id"), table_name="merchant_users")
    op.drop_table("merchant_users")
    op.drop_index(op.f("ix_merchant_policies_merchant_id"), table_name="merchant_policies")
    op.drop_table("merchant_policies")
    op.drop_table("merchants")
    op.drop_table("idempotency_records")
    op.drop_table("buyers")
    # ### end Alembic commands ###
